// Proxy Auto-Config file generated by autoproxy2pac, 2013-04-10 00:39:39
function FindProxyForURL(url, host) {
    var goagent = 'PROXY 127.0.0.1:8087';
    // Predefined rules, You could modify them by yourself.
    if (
            dnsDomainIs(host, '.google.com') ||
            dnsDomainIs(host, '.google-analytics.com') ||
            dnsDomainIs(host, '.googleapis.com') ||
            dnsDomainIs(host, '.googlecode.com') ||
            dnsDomainIs(host, '.googleusercontent.com') ||
            dnsDomainIs(host, '.gstatic.com') ||
            dnsDomainIs(host, '.wikipedia.org') ||
            dnsDomainIs(host, '.twimg.com') ||
            dnsDomainIs(host, '.ytimg.com') ||
            dnsDomainIs(host, '.fbcdn.net') ||
            shExpMatch(host, '*.google.com.*') ||
            host == 't.co' ||
            host == 'bit.ly' ||
            host == 'goo.gl' ||
            host == 'fb.me' ||
            host == 'wp.me' ||
            host == 'j.mp' ||
            host == 'ow.ly' ||
            host == 'po.st' ||
            host == 'bbc.in'
        )
    {
        return goagent;
    }

    return FindProxyForURLByAutoProxy(url, host);
}
return "DIRECT";
}
